#!/bin/bash

	###################################################
	#		Sistema Super Alfa		  #
	#	     Desenvolvedor: Grupo Alfa		  #
	#         Integrantes: Alexandre, Matheus,	  #
	#	      Sayyid, Wilson e  Tarcísio	  #
	#	          Professor: Thales		  #
	#	           Disciplina: FDP		  #
	#			Data:			  #
	###################################################

########################  Variáveis ###################################

usuario=Alfa
senha=senai123
sai=1
counter=0

########################## Tela de Login ###############################
while (( $sai != 0 )); do
clear
qnt=1

while (( $qnt <= 5 )); do
user=$(dialog --stdout --backtitle "Sistema Super Alfa"		\
		--inputbox "Entre com seu usuário:" 0 -15)

pass=$(dialog --stdout --backtitle "Sistema Super Alfa"		\
		--insecure --passwordbox " Entre com a sua senha:" 0 -15)

if [ $user == $usuario ]; then
	if [ $pass == $senha ]; then
		sai=0
		qnt=6

	else
		dialog --msgbox "Senha incorreta !!!" 0 -10
	fi
else
		dialog --msgbox "Usuário incorreto !!!" 0 -10
fi

let qnt=($qnt+1)
done
done

dialog --backtitle "Sistema Super Alfa" --msgbox "Acesso Permitido !!!" 0 0

menu

########################## Função Menu Principal ###########################
function menu () {
clear

mn=$(dialog --stdout --title "Gerenciamento do Sistema"\
	    --menu "Escolha uma opção" 0 0 0 	\
1 "Gerenciar Usuários"		\
2 "Gerenciar Grupos"		\
3 "Gerenciar Arquivos"		\
4 "Gerenciar Rede Local"	\
5 "Gerenciar Dispositivos"	\
6 "Sair")


case $mn in


1)menu1;;
2)menu2;; 
3)menu3;;
4)menu4;; 
5)menu5;; 
6)menu6;;
esac }
menu
function menu6 (){
(
while :
do
cat << EOF
XXX
$counter
Finalizando Processos ( $counter% ):
XXX
EOF

(( counter+=20 ))
[ $counter == 100 ] && break

sleep 1

done

) |
dialog --title "Aguarde um momento" --gauge "Please wait " 7 70 0
clear
exit
}


############################# Função Menu Usuário ##########################

function menu2 () {
clear
mn1=$(dialog --stdout --title "O que você deseja fazer?" \
             --menu "Escolha uma opção" 0 0 0 \
1 "Criar usuário"	\
2 "Deletar usuário"	\
3 "Renomear usuário"	\
4 "Voltar")

case $mn1 in
1)cuser;;
2)ruser;;
3)mvuser;;
4)menu;; 
esac

menu1
}
#menu1

######################  Função Criar Usuário  ###########################

function cuser (){
clear

user=$(dialog  --stdout  		\
	       --inputbox "Digite o nome do usuário a ser criado:"  0 0)

senha=$(dialog --stdout --insecure	\
	       --passwordbox "Digite a senha:" 0 0)

dialog --title "Confirmação" \
		--backtitle "Atenção" \
		--yesno "Voce tem certeza que deseja criar um usuário?" 7 50

if [ "$?" == "0" ]; then

useradd -m -d /home/$user -r -s /bin/bash $user;
(echo $senha; echo $senha) | passwd $user;
dialog --msgbox "Usuário criado com sucesso!" 0 0

else

dialog --msgbox "Procedimento Cancelado!" 0 0

fi

tail  -f /etc/passwd > out &

dialog --title "Lista de usuários" --tailbox out 0 0

menu1
}

#menu1

######################### Função Deletar Usuário #########################

function ruser (){
clear

user=$(dialog  --stdout  		\
	       --inputbox "Digite o nome do usuário a ser apagado:"  0 0)

dialog --title "Confirmação" \
		--backtitle "Atenção" \
		--yesno "Voce tem certeza que deseja deletar o usuário?" 7 50

if [ "$?" == "0" ]; then

deluser $user

dialog --msgbox "Usuário deletado com sucesso!" 0 0

else

dialog --msgbox "Procedimento Cancelado!" 0 0

fi

tail -f /etc/passwd > out1 &

dialog --title "Lista de usuários" --tailbox out1 0 0

menu1
}

#menu1
######################## Função Renomear Usuário  ###########################
function mvuser (){
clear

user=$(dialog  --stdout  		\
	       --inputbox "Digite o nome do usuário a ser modificado o nome:"  0 0)

mvuser=$(dialog  --stdout  		\
	       --inputbox "Digite o novo nome do usuário:"  0 0)

dialog --title "Confirmação" \
		--backtitle "Atenção" \
		--yesno "Voce tem certeza que deseja renomear o usuário?" 7 50

if [ "$?" == "0" ]; then

usermod -l $mvuser $user

dialog --msgbox "Usuário renomeado com sucesso!" 0 0

else

dialog --msgbox "Procedimento Cancelado!" 0 0

fi

tail -f /etc/passwd > out2 &

dialog --title "Lista de usuários" --tailbox out2 0 0

menu1
}

#menu1
###################  Função Menu de Arquivos  ################

function menu3 () {
clear
mn3=$(dialog --stdout --title "O que você deseja fazer?" \
             --menu "Escolha uma opção" 0 0 0 \
1 "Criar arquivo"	\
2 "Deletar arquivo "	\
3 "Renomear arquivo"	\
4 "Mover arquivo"	\
5 "Compactar arquivo"	\
6 "Descompactar arquivo" \
7 "Voltar")

case $mn3 in
1)carquivo;;
2)delarquivo;;
3)rearquivo;;
4)moarquivo;;
5)coarquivo;;
6)desarquivo;;
7)menu;; 
esac
}
menu3

######################  Função Criar Arquivo  ###########################

function carquivo (){
clear

arq=$(dialog  --stdout  		\
	       --inputbox "Digite o nome do arquivo a ser criado:"  0 0)

dialog --title "Confirmação" \
		--backtitle "Atenção" \
		--yesno "Voce tem certeza que deseja criar um arquivo?" 7 50

if [ "$?" == "0" ]; then

touch $arq

dialog --msgbox "Arquivo criado com sucesso!" 0 0

else

dialog --msgbox "Procedimento Cancelado!" 0 0

fi

ls -la > out4 &

dialog --title "Lista de arquivos" --tailbox out4 0 0

menu3
}

#menu3

######################  Função Deletar Arquivo  ###########################

function delarquivo (){

delarq=$(dialog  --stdout  		\
	       --inputbox "Digite o nome do arquivo a ser deletado:"  0 0)
rm $delarq

dialog --title "Confirmação" \
		--backtitle "Atenção" \
		--yesno "Voce tem certeza que deseja deletar o arquivo?" 7 50

if [ "$?" == "0" ]; then

rm $delarq

dialog --msgbox "Arquivo deletado com sucesso!" 0 0

else

dialog --msgbox "Procedimento Cancelado!" 0 0

fi

ls -la > out &

dialog --title "Lista de arquivos" --tailbox out 0 0

menu3
}

#menu3
######################  Função Renomear Arquivo  ###########################

function rearquivo (){
clear

rearq=$(dialog  --stdout  		\
	       --inputbox "Digite o nome do arquivo a ser renomeado:"  0 0)

novoarq=$(dialog  --stdout  		\
	       --inputbox "Digite o novo nome do arquivo:"  0 0)

dialog --title "Confirmação" \
		--backtitle "Atenção" \
		--yesno "Voce tem certeza que deseja renomear o arquivo?" 7 50

if [ "$?" == "0" ]; then

touch $novoarq $rearq

dialog --msgbox "Arquivo renomeado com sucesso!" 0 0

else

dialog --msgbox "Procedimento Cancelado!" 0 0

fi

ls -la > out6 &

dialog --title "Lista de arquivos" --tailbox out6 0 0
exit

menu3
}

#menu3

#######################  Função Mover Arquivo  ###########################

function  moarquivo() {

local f="$1"
local m="$0: file $f Falha  ao mover arquivo."
if [ -f $f ]
then
	/home/vagrant/ mv $FILE && m="$0: $f Arquivo movido."
else
	m="$0: $f Não é um arquivo."

fi

	dialog --title "Mover arquivo" --clear --msgbox "$m" 10 50
}

menu3

########### Comando para selecionar o arquivo com o Dialog ###################
FILE=$(dialog --title "Mover um arquivo" \
		--stdout --title "Por favor escolha um arquivo a ser movido"  \
		 --fselect /home/vagrant 14 48)

########## Comando para deletar o arquivo ###############################
[ ! -z $FILE ] && moarquivo "$FILE"

############################################################################

function menu1(){

		dialog --msgbox "Menu 2 !!!" 0 -10
}

function menu4(){
		dialog --msgbox "Menu 4 !!!" 0 -10

}
function menu5(){
		dialog --msgbox "Menu 5 !!!" 0 -10

}
