#!/bin/bash
clear
int=1
teste=0
tmp=0

while (( $int != 0 )); do
	read -p "Digite um numero" num[$teste]
	int=${num[$teste]}
	let teste=$teste+1
	t=$teste
	te=$teste-1
	tee=$teste-2
done

tmp=${num[$te]}

for (( w=1; w < $teste; w++ )); do
	if (( $tmp <= ${num[$tee]} )); then
		menor=$tmp
		let tee=$tee-1
	else 
		tmp=${num[$tee]}
		menor=$tmp
		let tee=$tee-1	
	fi
done

maiorOrd=$menor
let troca=$menor-1
for (( u=0; u < $teste; u++ )); do
	for (( y=0; y < $teste; y++ )); do
		if (( $maiorOrd <= ${num[y]} )); then
			maiorOrd=${num[$y]}
			x=$y
			maior[$t]=$maiorOrd
		fi
	done
	num[$x]=$troca
	let t=$t-1
	maiorOrd=$menor
done
echo ${maior[*]}
